Updates:  11/13/06 (John Weigand)     - added a usage function     - added the executtion of the check-vo-map file if it is an OSG       installation     - added creation of a link from the grid3-user-vo-map.txt file       to the new osg- suffixed one if it does not exist.     - added backups directory that will maintained a maximum of 10 backups  12/29/06 (John Weigand)     - added execution of configure_gip
r212 gums-client

diff --git a/src/main/scripts/gums-host-cron b/src/main/scripts/gums-host-cron
--- a/src/main/scripts/gums-host-cron
+++ b/src/main/scripts/gums-host-cron
@@ -1,33 +1,74 @@
 #!/bin/sh
+######################################################################
+
+VDT_LOCATION=MAGIC_VDT_LOCATION
+
 ###########################################################################
-# This process is intended to be run as a root cron process.
-#
-# It executes the GUMS client process in order to refresh the
-# following files from the GUMS server:
-#  1.  /etc/grid-security/grid-mapfile
-#      This refresh of the grid-mapfile will only occur when running in
-#      the gatekeeper PRIMA callout is NOT in effect based on the
-#      absence of the /etc/grid-security/gsi-authz.conf file.
-#
-#  2.  VDT_LOCATION/monitoring/grid3-user-vo-map.txt
-#      This refresh will always occur.
-#
-# This cron will perform this task as follows for each map file:
-#  - It will make a copy of the current files with a '.cronsaved' # suffix.  
-#  - The new map file will be created with a '.new' suffix.
-#  - If not successful, it will exit and cron should send an email regarding 
-#  - If successful, 
-#      it will check to see if the new file has changed and if so
-#        it will replace the current map file with  the '.new' file error.
-#       otherwise it will leave the map file alone.
-#      (Note: this is done to minimize the impact on the MonALISA 
-#             VO_Modules module in the case of the user-vo map file.
-#             It re-caches that file if the timestamp changes.)
+function usage {
+ echo "\
+
+ This script is intended to be run as a root cron process.
+
+ It executes the GUMS client script in order to refresh the
+ following files for a CE node from the site's GUMS server:
+
+  1. $MAPFILE
+      This refresh will only occur when the PRIMA callout is NOT in effect 
+      for the CE node, based on:
+      - the absence of the $PRIMA_CALLOUT file
+      - and the absence of the PRIMA callout string in the above conf file:
+          $PRIMA_CALLOUT_STRING
+
+  2. $INVERSEMAP
+      This refresh will always occur for an OSG site.
+      The criteria defining an OSG site is the presence of a
+      $OSG_SITE_CRITERIA file.
+
+  3. $SUPPORTEDVOS
+      This identifies the list of VOs that can be authorized bu this CE node
+      based on the either the gridmap file or GUMS server used for authorization
+      and the existence of a UNIX account for the VO members.
+      This refresh will always occur for an OSG site. 
+
+  4. $UNDEFINED
+      This identifies a list of UNIX accounts that can potentially be
+      authorized but do not exist and therefore the VO member will be 
+      unable to access services on this CE node.
+      This refresh will always occur for an OSG site. 
+
+ This script will perform the task as follows for each map file:
+  a. The GUMS client script will create a new map file with a '.new' suffix.
+  b. It will check to see if the '.new' file differs for the current file.
+  c. If a change has occurred:
+     - it will backup the current file in a directory called './$BACKUP_DIR'
+       (in the same directory as the map file) with a timestamped suffix 
+       indicating when it was replaced. 
+     - it will replace the current map file with  the '.new' file.
+     - a maximum of 10 backups will be maintained by the script
+  d. If no change has occured: 
+     - no replacement will occur and the '.new' file will be removed.
+  e. An empty '.last_checked' suffix map file will be created each time a map 
+     file is successfully checked in order to provide a visible indication of 
+     the currency of the data.
+
+ Usage: $PGM [--help | -help | -h ]
+"
+}
+
+###########################################################################
+# See the usage function for a general explanation
 #
 # The only required modification to this file is the setting of the
 # VDT_LOCATION variable.  No other environmental settings are required.
 # It does have to source the VDT_LOCATION/setup.sh file in order to
 # insure the VDT version of java is used.
+#
+# Note: The replacement of the map files only when a change has occured is
+#       done because some CE node components cache these map files and are
+#       designed to re-cache when the timestamp changes.
+#       - MonALISA does this with the $INVERSMAP file
+#       - Globus web services does this with the $MAPFILE when the
+#         default gridmap authz method is used.
 #
 # Updates:
 # 1. 9/28/2006 (John Weigand)
@@ -50,45 +91,83 @@
 #      of the $VDT_LOCATION/monitoring/osg-attributes.conf file.
 #      If this file does NOT exist, then the inverse map file will
 #      NOT be created.
-#   
+# 2. 11/13/06 (John Weigand)
+#    - added a usage function
+#    - added the executtion of the check-vo-map file if it is an OSG
+#      installation
+#    - added creation of a link from the grid3-user-vo-map.txt file
+#      to the new osg- suffixed one if it does not exist.
+#    - added backups directory that will maintained a maximum of 10 backups
+# 3. 12/29/06 (John Weigand)
+#    - added execution of configure_gip
 ###########################################################################
-######################################################################
 
-VDT_LOCATION=/storage/local/data1/osg-ce
-
-######################################################################
-######################################################################
+function logit {
+  ts=$(date  +'%Y-%m-%dT%H-%M-%S')  #--- timestamp for log file ---
+  echo "$ts $1" >>$LOGFILE
+}
+#-----------------
 function logerr {
-  echo "ERROR: The $PGM process failed.
-
-$1
-"
+  logit "ERROR: $1"
+  logit "$PGM process terminated prematurely"
+  logit "=============================================="
   exit 1
 }
 #-----------------------------
 function verify_permissions {
   if [ ! -f $1 ];then
     if [ ! -w $(dirname $1) ];then 
-      logerr "This process needs to modify or create several files.
-Access/permissions denied for file $1
-"
+      logit  "This process needs to modify or create several files."
+      logerr "Access/permissions denied for file $1"
     fi
   elif [ ! -w $1 ];then
-    logerr "This process needs to modify or create several files.
-
-Access/permissions denied for file $1
-"
+    logit  "This process needs to modify or create several files."
+    logerr "Access/permissions denied for file $1"
   fi
 }
 #-----------------------------
+function create_directory {
+  dir=$1
+  if [ ! -d $dir ];then
+    mkdir -p $dir
+  fi
+
+}
+#-----------------------------
 function replace_if_changed {
-  diff -q $1 $2 >/dev/null 2>&1
-  if [ "$?" = 1 ];then
-    cp -pf $2 $2.cronsaved
-    mv $1 $2
+  new=$1
+  current=$2
+  logit "Checking for changes in $current"
+  diff -q $current $new >/dev/null 2>&1
+  rtn=$?
+  if [ "$rtn" = "1" ];then
+    backupdir=`dirname $current`/$BACKUP_DIR
+    create_directory $backupdir
+    prefix=$backupdir/`basename $current`
+    backupfile=${prefix}.$BACKUP_DATE
+    logit "... changes have occurred"
+    logit "... backing up to: $backupfile"
+    logit "... version: $current"
+    cp -pf $current $backupfile
+    mv $new $current
+    #---- clean backup dir 10 copies only ---
+    MAX_BACKUPS=10
+    cnt=`ls ${prefix}.* 2>/dev/null  |wc -l |sed -e"s/ //g"`
+    rm_cnt=`expr $cnt - $MAX_BACKUPS`
+    if [ $rm_cnt -gt 0 ];then
+      for backup in `ls ${prefix}.* 2>/dev/null | head -$rm_cnt`
+      do
+        test  -f $backup  || continue
+        rm -f $backup
+        logit "... removed old backup file: $backup"
+      done
+    fi
+  else
+   logit "... no change"
   fi
   rm -f $1
   >$2.last_checked
+  logit "--------------------------------------"
 }
 
 #-------------------------------
@@ -103,29 +182,38 @@ function generate_grid_mapfile {
       GRID_MAP_USED=yes
     fi
   fi
+  if [ "$GRID_MAP_USED" = "no" ];then
+    logit "The PRIMA callout is in effect therefore no grid-mapfile is needed."
+    return
+  fi
 
   #--- generate grid-mapfile if callout not used --
-  if [ "$GRID_MAP_USED" = "yes" ];then
-    # this is in the event no grid-mapfile exists
-    if [ ! -e $MAPFILE ];then
-      touch $MAPFILE
-      chmod 644 $MAPFILE
-    fi
-    for file in $MAPFILE $MAPFILE_NEW $MAPFILE_SAVED 
-    do
-      verify_permissions $file
-    done
-    $GUMSDIR/gums-host generateGridMapfile >$MAPFILE_NEW 2>&1
-    if [ "$?" != "0" ];then
-      logerr "The GUMS client generateGridMapfile process failed while 
-attempting to generate the $MAPFILE file.
+  # this is in the event no grid-mapfile exists
+  if [ ! -e $MAPFILE ];then
+    touch $MAPFILE
+    chmod 644 $MAPFILE
+  fi
+  for file in $MAPFILE $MAPFILE_NEW
+  do
+    verify_permissions $file
+  done
+  script="$GUMSDIR/gums-host generateGridMapfile"
+  logit "--------------------------------------"
+  logit "Updating $(basename $MAPFILE)"
+  logit "RUNNING: $script"
+  $script  >$MAPFILE_NEW 2>>$LOGFILE
+  rtn=$?
+  logit "gums-host completed with return code: $rtn"
+  if [ "$rtn" != "0" ];then
+    logerr "The GUMS client generateGridMapfile process failed while attempting to generate the $MAPFILE file.
 
 ---- output --------------------------------------
 $(cat $MAPFILE_NEW)
 "
-    fi
-  replace_if_changed $MAPFILE_NEW $MAPFILE 
   fi
+
+  logit "--------------------------------------"
+  replace_if_changed $MAPFILE_NEW $MAPFILE 
 }
 
 #-------------------------------
@@ -169,7 +257,7 @@ function generate_user_vo_mapfile {
   # to the new name is complete and all software is
   # upgraded.
   #
-  for file in $INVERSEMAP $INVERSEMAP_NEW $INVERSEMAP_SAVED
+  for file in $INVERSEMAP $INVERSEMAP_NEW 
   do
     verify_permissions $file
   done
@@ -184,22 +272,74 @@ function generate_user_vo_mapfile {
     ln -s $INVERSEMAP $INVERSEMAP_DEPRECATED
   fi
 
-  if [ -e $INVERSEMAP ];then
-    $GUMSDIR/gums-host generateGrid3UserVoMap  >$INVERSEMAP_NEW 2>&1
-    if [ "$?" != "0" ];then
+  #--- generate the user-vo map file ----
+  script="$GUMSDIR/gums-host generateGrid3UserVoMap" 
+  logit "--------------------------------------"
+  logit "Updating $(basename $INVERSEMAP)"
+  logit "RUNNING: $script"
+  $script  >$INVERSEMAP_NEW 2>>$LOGFILE
+  if [ "$?" != "0" ];then
     logerr "The GUMS client generateGrid3UserVoMap process failed while 
 attempting to generate the $INVERSEMAP file.
 
 ---- output --------------------------------------
   $(cat $INVERSEMAP_NEW)
 " 
-    fi
-    replace_if_changed $INVERSEMAP_NEW $INVERSEMAP 
+  fi
+  logit "... $INVERSEMAP_NEW created"
+  logit "gums-host command completed successfully"
+  logit "--------------------------------------"
+
+  
+  # Check to see if all the username entries in the
+  # osg-user-vo-map.txt file have UNIX accounts and also create
+  # a osg-supported-vo-list.txt if changed
+
+  # --- verify installation supports this ---
+  script=$VDT_LOCATION/osg-vo-map/sbin/check-vo-map
+  if [ ! -x $script ];then
+    logit "ERROR: Installation misconfigured. Cannot find script ($script)"
+    return
+  fi
+  # --- if supported vo file does not exist, create empty one (1 time deal)
+  if [ ! -e $SUPPORTEDVOS ];then
+    touch $SUPPORTEDVOS
+  fi
+  # --- if supported vo file does not exist, create empty one (1 time deal)
+  if [ ! -e $UNDEFINED ];then
+    touch $UNDEFINED
   fi
 
+  logit "Validating  $(basename $INVERSEMAP_NEW)"
+  logit "RUNNING: $script"
+  $script --input $INVERSEMAP_NEW \
+         --output $INVERSEMAP_NEW.tmp \
+         --volist $SUPPORTEDVOS_NEW \
+         --undefined $UNDEFINED_NEW \
+         --log $LOGFILE
+  rtn=$?
+  logit "$(basename $script) RETURN CODE: $rtn"
+  logit "--------------------------------------"
+  
+  replace_if_changed $INVERSEMAP_NEW.tmp   $INVERSEMAP
+  replace_if_changed $SUPPORTEDVOS_NEW $SUPPORTEDVOS
+  replace_if_changed $UNDEFINED_NEW    $UNDEFINED
 
 }
-
+#------------------------------
+function run_configure_gip {
+  script=$VDT_LOCATION/vdt/setup/configure_gip
+  logit "--------------------------------------"
+  logit "Running $script"
+  if [ -x $script ];then
+    $script >>$LOGFILE 2>&1
+    rtn=$?
+    logit "$(basename $script) RETURN CODE: $rtn"
+  else
+  logit "WARNING: Script is not executable"
+  fi
+  logit "--------------------------------------"
+}
 
 #### MAIN ###############################################################
 PGM=$(basename $0)
@@ -209,46 +349,82 @@ GUMSDIR=$VDT_LOCATION/gums/bin
 
 MAPFILE=/etc/grid-security/grid-mapfile
 MAPFILE_NEW=$MAPFILE.new
-MAPFILE_SAVED=$MAPFILE.cronsaved
 
+#--- this files existence identifies if this is an OSG site or not ------
 OSG_SITE_CRITERIA=$VDT_LOCATION/monitoring/osg-attributes.conf
+
 INVERSEMAP_DEPRECATED=$VDT_LOCATION/monitoring/grid3-user-vo-map.txt
+
 INVERSEMAP=$VDT_LOCATION/monitoring/osg-user-vo-map.txt
 INVERSEMAP_NEW=$INVERSEMAP.new
-INVERSEMAP_SAVED=$INVERSEMAP.cronsaved
+
+SUPPORTEDVOS=$VDT_LOCATION/monitoring/osg-supported-vo-list.txt 
+SUPPORTEDVOS_NEW=$SUPPORTEDVOS.new
+
+UNDEFINED=$VDT_LOCATION/monitoring/osg-undefined-accounts.txt 
+UNDEFINED_NEW=$UNDEFINED.new
+
+LOGFILE=$VDT_LOCATION/monitoring/log/gums-host-cron.log
+
+BACKUP_DIR=backups
+BACKUP_DATE=$(date '+%Y-%m-%dT%H-%M-%S')
+
+#------------------------------
+#  check command line args 
+#------------------------------
+if [ $# -gt 0 ];then
+  usage
+  exit 1
+fi
 
 #------------------------------
 #  validate VDT_LOCATION  
 #------------------------------
 if [ ! -d $VDT_LOCATION ] || [ -z "$VDT_LOCATION" ];then
-  logerr "Invalid VDT_LOCATION($VDT_LOCATION)"
+  echo "ERROR: Invalid VDT_LOCATION($VDT_LOCATION)"
+  exit 1
 fi
 setup=$VDT_LOCATION/setup.sh
 if [ ! -r $setup ];then
-  logerr "Invalid OSG installation. Setup file ($setup) does not exist."
+  echo "ERROR: Invalid OSG installation. Setup file ($setup) does not exist."
+  exit 1
 fi
 source $setup
+
 
 #----------------------
 #  validate GUMS  
 #----------------------
 if [ ! -d $GUMSDIR ];then
-  logerr "Invalid GUMS VDT installation.
+  echo "Invalid GUMS VDT installation.
 The GUMS directory ($GUMSDIR) does not exist or is not readable.
 "
+  exit 1
 fi
+
+#----------------------------
+#  create log file directory 
+#----------------------------
+create_directory $(dirname $LOGFILE)
+
+logit "============================================"
+logit "$PGM STARTED"
 
 #--------------------
 #  gridmap file  
 #--------------------
 generate_grid_mapfile
 
-#-------------------------------------
-#  user-vo map file if an OSG site ---
-#-------------------------------------
+#-----------------------------------------------------
+#  user-vo map & supported vo files if an OSG site ---
+#-----------------------------------------------------
 if [ -e $OSG_SITE_CRITERIA ];then
   generate_user_vo_mapfile
+  run_configure_gip
 fi
+
+logit "$PGM COMPLETED"
+logit "============================================"
 
 exit 0
 
